linters:
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - exhaustive
    - gochecknoinits
    - gocritic
    - goimports
    - makezero
    - misspell
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - unconvert
